sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t omarhussein2111/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true omarhussein2111/docker-react npm run test 