name: React-Project-CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build Docker image
        run: docker build -t omarhussein2111/docker-react -f Dockerfile.dev .
      - name: Run tests
        run: docker run -e CI=true omarhussein2111/docker-react npm run test